package com.essence.dao;

import com.essence.pojo.Item;
import java.util.List;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    int deleteByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    Item selectByPrimaryKey(String itemid);
   List< Item>selectByOrders(String ordersid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    List<Item> selectAll();
    
    int updateByPrimaryKey(Item record);
}