package com.essence.pojo;

import java.util.Date;

public class Address {
   
    private String addressid;

 
    private String userid;

    
    private String contactname;

   
    private String contactphone;

   
    private String province;

  
    private String city;

   
    private String detailaddr;

  
    private String status;

    
    private Date createtime;

    public String getAddressid() {
        return addressid;
    }

    
    public void setAddressid(String addressid) {
        this.addressid = addressid == null ? null : addressid.trim();
    }

   
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userId
     *
     * @param userid the value for address.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.contactName
     *
     * @return the value of address.contactName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.contactName
     *
     * @param contactname the value for address.contactName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.contactPhone
     *
     * @return the value of address.contactPhone
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.contactPhone
     *
     * @param contactphone the value for address.contactPhone
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone == null ? null : contactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detailAddr
     *
     * @return the value of address.detailAddr
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getDetailaddr() {
        return detailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detailAddr
     *
     * @param detailaddr the value for address.detailAddr
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setDetailaddr(String detailaddr) {
        this.detailaddr = detailaddr == null ? null : detailaddr.trim();
    }

  
    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.createTime
     *
     * @return the value of address.createTime
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.createTime
     *
     * @param createtime the value for address.createTime
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}