package com.essence.pojo;

import org.hibernate.validator.constraints.NotEmpty;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    @NotEmpty(message="用户名不能为空~")
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPwd
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    @NotEmpty(message="密码不能为空~")
    private String adminpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPwd
     *
     * @return the value of admin.adminPwd
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPwd
     *
     * @param adminpwd the value for admin.adminPwd
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd == null ? null : adminpwd.trim();
    }
}