package com.essence.pojo;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.collectionId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String collectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.collectionId
     *
     * @return the value of collection.collectionId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.collectionId
     *
     * @param collectionid the value for collection.collectionId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setCollectionid(String collectionid) {
        this.collectionid = collectionid == null ? null : collectionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.userId
     *
     * @return the value of collection.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.userId
     *
     * @param userid the value for collection.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.productId
     *
     * @return the value of collection.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.productId
     *
     * @param productid the value for collection.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }
}