package com.essence.pojo;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.goodsId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.color
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productNum
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private Integer productnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productId
     *
     * @return the value of product.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productId
     *
     * @param productid the value for product.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.goodsId
     *
     * @return the value of product.goodsId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.goodsId
     *
     * @param goodsid the value for product.goodsId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid == null ? null : goodsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.color
     *
     * @return the value of product.color
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.color
     *
     * @param color the value for product.color
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.size
     *
     * @return the value of product.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.size
     *
     * @param size the value for product.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productNum
     *
     * @return the value of product.productNum
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public Integer getProductnum() {
        return productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productNum
     *
     * @param productnum the value for product.productNum
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setProductnum(Integer productnum) {
        this.productnum = productnum;
    }
}