package com.essence.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)//ºöÂÔÎ´ÖªÊôÐÔ
public class Shoppingcart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.shoppingCarId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String shoppingcarid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.productNum
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private Integer productnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.color
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.price
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.isCheck
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private Integer ischeck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.totalMoney
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private Double totalmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.shoppingCarId
     *
     * @return the value of shoppingcart.shoppingCarId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getShoppingcarid() {
        return shoppingcarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.shoppingCarId
     *
     * @param shoppingcarid the value for shoppingcart.shoppingCarId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setShoppingcarid(String shoppingcarid) {
        this.shoppingcarid = shoppingcarid == null ? null : shoppingcarid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.userId
     *
     * @return the value of shoppingcart.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.userId
     *
     * @param userid the value for shoppingcart.userId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.productId
     *
     * @return the value of shoppingcart.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.productId
     *
     * @param productid the value for shoppingcart.productId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.productNum
     *
     * @return the value of shoppingcart.productNum
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public Integer getProductnum() {
        return productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.productNum
     *
     * @param productnum the value for shoppingcart.productNum
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setProductnum(Integer productnum) {
        this.productnum = productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.size
     *
     * @return the value of shoppingcart.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.size
     *
     * @param size the value for shoppingcart.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.color
     *
     * @return the value of shoppingcart.color
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.color
     *
     * @param color the value for shoppingcart.color
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.price
     *
     * @return the value of shoppingcart.price
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.price
     *
     * @param price the value for shoppingcart.price
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.isCheck
     *
     * @return the value of shoppingcart.isCheck
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public Integer getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.isCheck
     *
     * @param ischeck the value for shoppingcart.isCheck
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setIscheck(Integer ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.totalMoney
     *
     * @return the value of shoppingcart.totalMoney
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.totalMoney
     *
     * @param totalmoney the value for shoppingcart.totalMoney
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }
}