package com.essence.pojo;

public class Showpic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column showpic.showPicId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String showpicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column showpic.showPicType
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String showpictype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column showpic.showPicName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String showpicname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column showpic.showPicId
     *
     * @return the value of showpic.showPicId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getShowpicid() {
        return showpicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column showpic.showPicId
     *
     * @param showpicid the value for showpic.showPicId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setShowpicid(String showpicid) {
        this.showpicid = showpicid == null ? null : showpicid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column showpic.showPicType
     *
     * @return the value of showpic.showPicType
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getShowpictype() {
        return showpictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column showpic.showPicType
     *
     * @param showpictype the value for showpic.showPicType
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setShowpictype(String showpictype) {
        this.showpictype = showpictype == null ? null : showpictype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column showpic.showPicName
     *
     * @return the value of showpic.showPicName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getShowpicname() {
        return showpicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column showpic.showPicName
     *
     * @param showpicname the value for showpic.showPicName
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setShowpicname(String showpicname) {
        this.showpicname = showpicname == null ? null : showpicname.trim();
    }
}