package com.essence.pojo;

public class Size {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column size.sizeId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String sizeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column size.typeId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column size.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column size.sizeId
     *
     * @return the value of size.sizeId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getSizeid() {
        return sizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column size.sizeId
     *
     * @param sizeid the value for size.sizeId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setSizeid(String sizeid) {
        this.sizeid = sizeid == null ? null : sizeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column size.typeId
     *
     * @return the value of size.typeId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column size.typeId
     *
     * @param typeid the value for size.typeId
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column size.size
     *
     * @return the value of size.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column size.size
     *
     * @param size the value for size.size
     *
     * @mbg.generated Thu Aug 16 10:56:00 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }
}